#!/usr/bin/env bash

function _apex_profile {
  local shome="${_apex_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  APEX_VERSION="0.15.0"
}

_apex_profile
