#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_apex="$(apex version 2>/dev/null | awk '{print $3}' || true)"
  jq -n --arg apex "$ver_apex" '{apex: $apex}'
}

version "$@"
